version: '3.7'
services:
  bot_postgres:
    image: postgres:11
    environment:
      POSGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30

  bot:
    container_name: curs_bot
    image: curs
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py
    environment:
      PYTHONUNBUFFERED: 1