version: '3.7'
services:
  curs_bot_postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: curs_bot
      POSTGRES_PASSWORD: postgres
    ports:
      - '54300:5432'
